# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # NOTE: GitHub Actions dependencies not included to many conflicts with zizmor scans.

  # Python dependencies (pip ecosystem for uv projects)
  - package-ecosystem: pip
    directory: /
    rebase-strategy: auto
    target-branch: main
    schedule: # dependabot does not support cron
      interval: monthly
      time: "12:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 3
    groups:
      python-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - ml_ajourhold* # Exclude the local package itself
    cooldown:
      default-days: 7

  # Docker - Devcontainers
  - package-ecosystem: "devcontainers"
    directory: /
    rebase-strategy: auto
    target-branch: main
    schedule:
      interval: monthly
      time: "18:00"
      timezone: Europe/Oslo
    cooldown:
      default-days: 7
# TODO: Check if adding Docker ecosystem would be smart.
