name: CI | Docker Build and Test
# TODO: remove multistage/standalone

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435   # v3.11.1

    - name: Build and export
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83   # v6.18.0
      with:
        tags: ml_ajourhold:latest
        cache-from: type=gha,scope=ml_ajourhold
        cache-to: type=gha,mode=min,scope=ml_ajourhold
        outputs: type=docker,dest=/tmp/ml_ajourhold.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ml_ajourhold
        path: /tmp/ml_ajourhold.tar

  test:
    name: test image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: ml_ajourhold
        path: /tmp

    - name: Load images
      run: |
        docker load --input /tmp/ml_ajourhold.tar
        docker image ls -a

    - name: Test command line
      run: python --version

    - name: Test Docker compose
      run: |
        docker compose up -d
        docker compose down
